apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: ${CLICKHOUSE_USER}
      defaultDatabase: ${CLICKHOUSE_DB}
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
